### ISSUE TITLE
plugin: Parameter Automation

### ISSUE THREAD

**Issue by zhiweigan** [CharlesHolbrow/cybr#14]
The client currently does not have a way to specify a change in a plugin value at a specified time time. 

The most basic of solution to this problem would be something like this:
```javascript
fluid.plugin.setParam('param1', val, effectTime) //or effectBeat
```

Should we provide an option for the change to be a change over time? If so how should this be implemented? Ideas:
```javascript
fluid.plugin.setParam('param 1', val, 'line', startTime, endTime)
fluid.plugin.setParam('param 1', val, 'line', lead_up_time, effectTime) // should we make it a lead-up time instead?
fluid.plugin.setParam('param 1', val, 'step', effectTime)
```
A settings object, so 
```javascript
fluid.plugin.setParam('param 1', val, settings={type: 'line', startTime, endTime})
```
This might be more versatile?

Currently setParam changes the plugin for the whole track, and does not take into consideration when a parameter might be set. e.g.
```javascript
... some midi notes created (lets call this set of notes x)
fluid.plugin.setParam('param1', val)
... other notes created that want 'param' to be set to val
```

Would also set 'param1' to val for x. For the 'step' option, this might be a nice feature to have since then the user wouldn't have to check the exact time they want to do this, and they can instead rely on the fluid engine to be "smart" and do it for them. Similarly, we need to think of a way to specify when the parameter value starts changing if the user chooses the 'line' setting. 

We could also consider letting the user set multiple parameters at once (I don't think regular waveform supports this so it might be cool to do it) with an object if we want to link settings together? Like
```javascript
fluid.plugin.setParam({'param1' : val}, {'param2': val}, settingsObject)
```
Though this could also be achieved by using a settings object that is reused for every similar setParam call like:
```javascript
settingsObject = {time, 'step' ... }
fluid.plugin.setParam('param1', val, settingsObject)
fluid.plugin.setParam('param2', val, settingsObject)
```

Finally, do we need to consider if a user selects two plugins? Then we have no way of selecting which plugin's parameters we want to change.

**Comment by zhiweigan** [comment]
functions:
```javascript
audiotrack.select() //USES trackName 
audiotrack.insertWav() //USES trackName 
midiclip.clear()
midiclip.select()
midiclip.note() //uses selected audiotrack
midiclip.create() //USES trackName 
plugin.select() //uses selected audiotrack
plugin.setParam() //uses selected audiotrack
plugin.save()
plugin.load() //uses selected audiotrack
plugin.loadTrkpreset() //uses selected audiotrack
plugin.addpath()
sampler.add() //uses selected audiotrack
sampler.clearAll() //uses selected audiotrack
transport.play()
transport.stop()
transport.loop()
transport.to()
global.save()
global.cd()
global.activate()
```

Only two functions (insertWav and midiclip.create) actually use trackName. I can't really think of any compelling arguments for why we would opt to stick with keeping trackName as a parameter.

One problem I ran into when I was writing an example and reading examples is that I would often be confused whether or not I would have to select an audiotrack before I’d try to do anything, so maybe removing the feature to specify trackName would be a good idea for streamlining the workflow.

Maybe we can make a new function called “audiotrack.insertWavWithTrack” that also creates a track while inserting (same with midiclip.create) just in case the user is doing a lot of this. Otherwise, it would be more code efficient in general to select an audiotrack beforehand.

**Comment by zhiweigan** [comment]
I have tested basic functionality but I will do more testing for edge cases before I make a pull request.

**Comment by CharlesHolbrow** [comment]
```
setParamNormalized(paramName, normalizedValue)
setParamExplicit(paramName, paramValue)
setParamNormalizedAt(paramName, normalizedValue, timeInQuarterNotes = 0, curve = 0)
setParamExplicitAt(paramName, paramValue, timeInQuarterNotes = 0, curve = 0)
```
