### ISSUE TITLE
Groove

### ISSUE THREAD

**Issue by zhiweigan** [CharlesHolbrow/cybr#19]
Lots of audio workstations have functionality to add grooves, i.e. swing, hip hop. I have to figure out a suitable interface for this, and implement it.

What would a good interface for grooves have?
- Parameter tuning
- The ability to specify your own groove
- Groove extraction?
- Adding, saving and loading groove presets

Implementation on Client Side:
```javascript
groove(notesObject, "swing", p1, p2, p3) directly changing the notes.
```

What presets should I have?
- Swing
- Hip hop 
- Latin

How would groove presets be stored and parsed?
Waveform saves them like this:
```xml
<GROOVETEMPLATE name="test" numberOfNotes="8" notesPerBeat="1">
    <SHIFT delta="0.0"/>
    <SHIFT delta="-0.036"/>
    <SHIFT delta="0.0"/>
    <SHIFT delta="-0.004"/>
    <SHIFT delta="0.004"/>
    <SHIFT delta="-0.002"/>
    <SHIFT delta="0.0"/>
    <SHIFT delta="0.022"/>
  </GROOVETEMPLATE>
```
The groove is applied such that the start of each beat is shifted by "delta" and loops around once all deltas have been iterated. From some testing, it seems like it disregards the time signature, which is good.
What datatype should we use to store these?
- In some sort of a javascript file, like recipes
  - We can directly store objects like those listed below
  - Easier to edit after extraction (is this needed?)

How would the user be able to specify their own groove?
- Groove extraction
- A possible method:
```javascript
gTimeLib = {'a': -1, 'b': 0}; // a = ahead of the beat, b = in front of the beat
gVeloLib = {'a':100, 'b': 60}; 
// both these libraries can be multiplied by a multiplier supplied by the user
rhythm     = "1234";
groovetime = "abab";
groovevelo = "abab"; //1, 3 are accented
random = 0.2;
```

**Comment by CharlesHolbrow** [comment]
closed by cbbfa103e6dd1f725742efae07d4a7df034633ef
