### ISSUE TITLE
Ensure that new fluid.setParam server handler can still save/load presets. 

### ISSUE THREAD

**Issue by CharlesHolbrow** [CharlesHolbrow/cybr#20]
The new setParam handler on the server adds an automation points instead of setting the parameter explicitly. 

Verify that we can still create presets. Write test a script that:

1. loads an inernal plugin (like delay or 4osc).
1. calls setParam on some parameters 
1. saves a plugin preset
1. look at the plugin xml. does it have the updated parameters?

(I'm worried that because the parameter is being set on the track, and not IN the plugin, the updated value will not be reflected in the preset)

**Comment by zhiweigan** [comment]
The preset file looks like this, with the automation curve property. I think this is alright for our purposes?

```xml
<PRESET name="test-preset2.trkpreset" filename="test-preset2.trkpreset"
        path="/Users/zhiweigan/Documents/cybr/Builds/MacOSX/build/Debug"
        tags="cybr">
  ...
    <AUTOMATIONCURVE paramID="ampAttack">
      <POINT t="0.0" v="0.1000000014901161" c="0.0"/>
      <POINT t="0.5" v="19.66147232055664" c="0.300000011920929"/>
    </AUTOMATIONCURVE>
...
```

**Comment by CharlesHolbrow** [comment]
My instinct is that setting a parameter value, and adding an automation point are two distinct actions, and should have two separate implementations. 

It also seems a little strange to me to save automation info with a preset. Presets should be portable between sessions, while automation should only apply to a specific session. We probably don't want loading a preset to load the automation in to the track? That might be useful in some circumstances, but I think it would be a surprise to most users.

perhaps two methods like this:

```javascript
fluid.plugin.setParam(paramName, value)
fluid.plugin.setParamAt(paramName, value, time, curve)
```
