### ISSUE TITLE
Ensure that FluidIpc objects are not leaking

### ISSUE THREAD

**Issue by CharlesHolbrow** [CharlesHolbrow/cybr#39]
When a TCP connection is accepted, the `FluidIpcServer::createConnectionObject` method adds a `FluidIpc` to a `std::map<int, FluidIpc>`  member variable. (https://github.com/CharlesHolbrow/cybr/blob/65b8c944d6c7ffeff5d4e80fadda8b337b606004/Source/FluidIpcServer.cpp#L18)

It doesn't look like the `FluidIpc` objects are being cleaned up. One way to verify is to write noisy constructors and destructors.

Just because a `FluidIpc` destructor is getting called does not mean that the object is being removed from the `std::map`. I think there might be invalid objects sticking around in the map, even after the connection has closed - I don't see them being removed from the map anywhere. 

So there are two goals
1. Ensure that the `FluidIpc` objects are getting destroyed. Just because the `connectionLost()` method is called does not mean that the object has been destroyed, and is no longer in memory.
1. Ensure that finished `FluidIpc` objects are removed from the `std::map` after they are no longer needed.

`FluidIpc` Objects may need to store their id, so that they can easily delete themselves from the map.

Other thoughts:
It is conceivable that the integers would wrap because they are being constantly incremented with each connection. What happens when `ipc_num` exceeded 2^16-1 `(&ipcMap[ipc_num++];`)? it's worth thinking through how this would play out, as it is not inconcievable that a server would handle this many connections.

**Comment by CharlesHolbrow** [comment]
Note: you will need to re-open the xCode session from the projucer. This will add the FluidIpcServer to the xCode project.

**Comment by CharlesHolbrow** [comment]
(oops - put this in the wrong thread, moving it here)
@zhiweigan It looks like this is the callback that fires when a connection closes:

https://github.com/CharlesHolbrow/cybr/blob/ab9da36db86422c4b83f6e9cf2882cc729654322/Source/FluidIpcServer.cpp#L55-L57

Is that where the call to `fluidIpcServer->removeIpcConn(ipc_num);` should be? If the object are only getting removed from the map when the connections open, there I think there would still be a memory leak.

**Comment by zhiweigan** [comment]
@CharlesHolbrow Oh my gosh sorry that was an accident, I think I made a mistake when I was copy-pasting something and I didn't check. Should I make another pull request?

**Comment by CharlesHolbrow** [comment]
Yes please!
