### ISSUE TITLE
cybr `/plugin/select` handler fails with larger indexes

### ISSUE THREAD

**Issue by CharlesHolbrow** [CharlesHolbrow/cybr#72]
The following code is handled correctly:

```javascript
const msg = [
  fluid.plugin.select('#TCompressor', 'vst', 0),
  fluid.plugin.select('#TCompressor', 'vst', 1),
];
new fluid.Client().send(msg)
```

However, when the second selection id is higher, the `cybr` only inserts one additional plugin.

```javascript
const msg = [
  fluid.plugin.select('#TCompressor', 'vst', 0),
  fluid.plugin.select('#TCompressor', 'vst', 3), // This inserts and selects a second instance, 
];
new fluid.Client().send(msg)
```
This means that we can get surprising results when attempting to select a 3rd plugin when only one exists. 

The handler on the server-side should create as many instances of the plugin as needed in order to select the one with the supplied index. 

```javascript
// Key:
// v = volume plugin
// V = volume plugin (selected)
// s = "synth" vst plugin
// S = "synth" vst plugin (selected)
// f = an "FX" plugin
// F = an "FX" plugin (selected)
//
// 
// Example - a synth, followed by two effect plugins and a (selected) volume plugin:
// state: sffV 
fluid.track.select('synth', 'vst', 0);
// state: Sffv
fluid.track.select('FX', 'vst', 1);
// state: sfFv
fluid.track.select('synth', 'vst', 2); // create two additional instances juest before the volume plugin, selecting the correct one
// current result state: sffSv
// correct result state: sffsSv
```

**TODO:**

- Make sure that the handler inserts the correct number of plugins, and that the correct one is 'selected' when the command completes. 
- Note that the current behavior of inserting volume plugins is a little strange (perhaps buggy) when we select an nth volume plugin

```javascript
// state: sffv
fluid.plusin.select('volume', 'tracktion', 1)
// current result state: sffVv
```
Notice that the volume plugin in the `0` position is selected even though we `select`ed the with `1` as the id. This is because all new plugins are inserted just before the first instance of a volume plugin. This is an acceptable bug for now.

```javascript
// state: sffv
fluid.plugin.select('volume', 'tracktion', 3);
// desired state: sffvvVv // this is an acceptable bug for now, unless there is a simple and reliable fix
fluid.plugin.select('volume', 'tracktion', 3);
// desired state: sffvvvV // the second time it will work as expected
```

**Comment by zhiweigan** [comment]
I could not think of an easy fix for the volume plugin bug off the top of my head, but I can't think of a reason why I would ever want more than one volume plugin, so I decided to leave it as well.

**Comment by CharlesHolbrow** [comment]
Great. Thanks for this.
